# Site settings
title: Jason Hogrefe
email: hogrefejason@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Seeing red in Ruby! This site will track my progress as I jump
  into web programming and beyond...
url: "http://jhogrefe.github.io"
twitter_username: https://twitter.com/MacAppware
github_username:  jhogrefe

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "page"